version: "3.3"

services:
  traefik:
    image: "traefik:v2.3"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
#      - "--certificatesresolvers.entregas.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      # lo que se encuentra [cambiar] hay que cambiarlo por el nombre del certificado
      - "--certificatesresolvers.[cambiar].acme.email=tu@correo.com"
      - "--certificatesresolvers.[cambiar].acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.[cambiar].acme.httpchallenge.entrypoint=web"
      - "--pilot.token=token de pilot"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    labels:
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.deny-ip=github.com/notsureifkevin/denyip"
      - "traefik.http.middlewares.latency-check.circuitbreaker.expression=LatencyAtQuantileMS(50.0) > 100" # No llamar a servicios insalubres
      - "traefik.http.middlewares.test-compress.compress=true" # Comprimir la respuesta antes de enviarla al cliente
      - "traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=2000000" #Sets the maximum request body to 2Mb
      - "traefik.http.middlewares.autodetect.contenttype.autodetect=false" #Manejo de la detección automática de ContentType
      - "traefik.http.middlewares.test-inflightreq.inflightreq.amount=10" #Limitar el número

  waf:
    build: .
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.waf.rule=Host(`nombre.de.dominio`)'
      - "traefik.http.routers.waf.entrypoints=websecure"
      - "traefik.http.routers.waf.tls=true"
      - "traefik.http.routers.waf.tls.certresolver=entregas"
      - "traefik.http.middlewares.latency-check.circuitbreaker.expression=LatencyAtQuantileMS(50.0) > 100" # No llamar a servicios insalubres
      - "traefik.http.middlewares.test-compress.compress=true" # Comprimir la respuesta antes de enviarla al cliente
      - "traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=2000000" #Sets the maximum request body to 2Mb
      - "traefik.http.middlewares.autodetect.contenttype.autodetect=false" #Manejo de la detección automática de ContentType
      - "traefik.http.middlewares.test-inflightreq.inflightreq.amount=10" #Limitar el número
